### ISSUE TITLE
Picker vails with nil-value-issue

### ISSUE THREAD

**Issue by Weyaaron** [GustavoKatel/telescope-asynctasks.nvim#4]
Dear community,

thanks for providing this plugin, its appreciated! 
Unfortunately, it does not execute consistently. Calling ":Telescope asynctasks" fails with the following error: 
```
E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/command.lua:192: attempt to call a nil value 
```
![image](https://user-images.githubusercontent.com/52529582/162225897-e8319ce5-127e-406c-9a94-7dba7b716f7f.png)

It used to run once, but fails more often than not. I use the latest version of this plugin and the following neovim-version:

NVIM v0.6.0-dev+467-g30af69509
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by aaron@manjaro

Features: +acl +iconv +tui

**Comment by Weyaaron** [comment]
I found some more kontext: 
![image](https://user-images.githubusercontent.com/52529582/162381612-1389aa47-95eb-404f-b0aa-2f1f0f11c3fc.png)

**Comment by GustavoKatel** [comment]
hi the correct call is `:Telescope asynctasks all`. Let me know if that works for you

edit: added an example in the readme for future users

**Comment by Weyaaron** [comment]
This works out, thanks for the help!
